# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZZL3Rv1ZPs238ZuF-0Akh2LYZS0ak50
"""

import pandas as pd
baza={
    "FISH":["Xonqulov Muhammadjon" ,"Yusupov Dilyorbek" , "Xoshimov Behruz" , "Abdusattorova Mubina" , "Umarova Sohiba" ,"Sobirov Og'abek" , "Zohidov Mardon", "Sharipov Burhonjon" , "Alijonova Marjona" , "Sodiqova Ruxsora" ],
    "Yoshi": [ "19" , "18" , "14" , "16" , "12" , "13" , "15" , "14" , "17", "16"  ] ,
    "Jinsi": [ "o'g'il bola" , "o'g'il bola" , "o'g'il bola" , "qiz bola" , "qiz bola" , "o'g'il bola" , "o'g'il bola" , "o'g'il bola" , "qiz bola" , "qiz bola"],
    "Maktab raqami":[ "36" ,"18" , "29" , "45" , "25" , "13" , "31" , "30" , "16" , "47"]

}
df=pd.DataFrame(baza)
print(df)

df.to_excel("baza.xlsx")

filtr=df.loc[(df["Jinsi"]== "o'g'il bola")& (df["Yoshi"]=="19")]
print(filtr)

